### ISSUE TITLE
Problem with "

### ISSUE THREAD

**Issue by michelpereira** [WarWithinMe/xVim#10]
Hi.
When I'm editing a text and I type a function like:
printf("Text");

I got a crash when typing **"**, here it is:

UNCAUGHT EXCEPTION (NSRangeException): -[__NSCFConstantString characterAtIndex:]: Range or index out of bounds
UserInfo: (null)
Hints: None
Backtrace:
  0  0x00007fff925b9faa __exceptionPreprocess (in CoreFoundation)
  1  0x00007fff8c2d7d5e objc_exception_throw (in libobjc.A.dylib)
  2  0x00007fff925b9dfa +[NSException raise:format:arguments:](in CoreFoundation)
  3  0x00007fff925b9d84 +[NSException raise:format:](in CoreFoundation)
  4  0x00007fff92577a9e -[__NSCFString characterAtIndex:](in CoreFoundation)
  5  0x000000010cd9f92e -[DVTSourceTextViewHook keyDown:](in XVim)
  6  0x00007fff92c90b44 -[NSWindow sendEvent:](in AppKit)
  7  0x00007fff92c2916d -[NSApplication sendEvent:](in AppKit)
  8  0x000000010a4d3a11 -[IDEApplication sendEvent:](in IDEKit)
  9  0x00007fff92bbf1f2 -[NSApplication run](in AppKit)
 10  0x00007fff92e3db88 NSApplicationMain (in AppKit)
 11  0x0000000109bcbeec (in Xcode)

**Comment by jordwalke** [comment]
Possibly related, in the newest XCode, when XCode completes a quote pair

" -->  "|"    (where | is your cursor)

When you press quote again, xVim oddly enters command mode again.
