### ISSUE TITLE
Build fails on master branch

### ISSUE THREAD

**Issue by jordwalke** [WarWithinMe/xVim#3]
It looks for a file called keymap but there is only a file called keymap-example.
Renaming it makes the build pass.

**Comment by WarWithinMe** [comment]
Make readme more accurate :
When building from source, one should use **xVim-Release Scheme**

That xVim-WWM-Release Scheme is kinda personal XD...

**Comment by jordwalke** [comment]
"you may want to build it with xVim-Release Scheme"

It sounded optional :)
